language: java
sudo: false
install: true

jdk:
  - oraclejdk8
  
install:
  - mvn install:install-file -Dfile=petClinic_BENOIT-ejb/src/main/resources/META-INF/lib/generic-commons-tools.jar -DgroupId=net.entetrs.commons -DartifactId=generic-common-tools -Dversion=1.0 -Dpackaging=jar
  - mvn install:install-file -Dfile=petClinic_BENOIT-ejb/src/main/resources/META-INF/lib/jsf-commons-tools.jar -DgroupId=net.entetrs.commons -DartifactId=jsf-common-tools -Dversion=1.0 -Dpackaging=jar
  - mvn install:install-file -Dfile=petClinic_BENOIT-ejb/src/main/resources/META-INF/lib/jpa-commons-tools.jar -DgroupId=net.entetrs.commons -DartifactId=jpa-common-tools -Dversion=1.0 -Dpackaging=jar

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
  - mvn cobertura:cobertura
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/fr/zyra
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
